# Generated by Django 5.1.4 on 2025-01-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids'), ('Unisex', 'Unisex')], max_length=10)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price', models.IntegerField()),
                ('sale_price', models.IntegerField(blank=True, null=True)),
                ('stock_quantity', models.IntegerField()),
            ],
        ),
    ]
